/* ============================================================
   LISTA DE PRESENTES — LISTA REAL DO CASAL
   ============================================================ */

const PRESENTES = [
  {
    id: "p1",
    nome: "Conjunto de Panelas",
    descricao: "Conjunto de panelas antiaderente",
    preco: 399,
    loja: "",
    categoria: "Cozinha",
    emoji: "🍳",
    img: "img/produtos/conjunto-panelas.jpg",
    link: "",
  },
  {
    id: "p2",
    nome: "Airfryer Tipo Forno",
    descricao: "Airfryer tipo forno Mondial",
    preco: 549,
    loja: "",
    categoria: "Eletroportáteis",
    emoji: "🍟",
    img: "img/produtos/airfryer-mondial.jpg",
    link: "",
  },
  {
    id: "p3",
    nome: "Liquidificador 1500W",
    descricao: "Liquidificador Philco 1500W",
    preco: 219,
    loja: "",
    categoria: "Eletroportáteis",
    emoji: "🥤",
    img: "img/produtos/liquidificador-philco.jpg",
    link: "",
  },
  {
    id: "p4",
    nome: "Robô Aspirador",
    descricao: "Robô aspirador Xiaomi",
    preco: 1299,
    loja: "",
    categoria: "Casa",
    emoji: "🧹",
    img: "img/produtos/robo-aspirador-xiaomi.jpg",
    link: "",
  },
  {
    id: "p5",
    nome: "Sofá Retrátil",
    descricao: "Sofá retrátil e reclinável",
    preco: 1899,
    loja: "",
    categoria: "Casa",
    emoji: "🛋️",
    img: "img/produtos/sofa-retratil.jpg",
    link: "",
  },
  {
    id: "p6",
    nome: "Cotas para a Lua de Mel",
    descricao: "Ajude com qualquer valor para nossa lua de mel! 💛",
    preco: 0,
    loja: "Pix / Transferência",
    categoria: "Lua de Mel",
    emoji: "✈️",
    img: "img/produtos/lua-de-mel.jpg",
    link: "",
  },
  {
    id: "p7",
    nome: "Lava Louças",
    descricao: "Lava louças Samsung",
    preco: 2799,
    loja: "",
    categoria: "Eletroportáteis",
    emoji: "🍽️",
    img: "img/produtos/lava-loucas-samsung.jpg",
    link: "",
  },
  {
    id: "p8",
    nome: "Jogo de Cama",
    descricao: "Jogo de cama queen",
    preco: 259,
    loja: "",
    categoria: "Cama & Banho",
    emoji: "🛏️",
    img: "img/produtos/jogo-de-cama.jpg",
    link: "",
  },
  {
    id: "p9",
    nome: "Filtro de Água de Galão",
    descricao: "Filtro de água de galão Philco",
    preco: 149,
    loja: "",
    categoria: "Casa",
    emoji: "💧",
    img: "img/produtos/filtro-agua-philco.jpg",
    link: "",
  },
  {
    id: "p10",
    nome: "Sanduicheira Grill",
    descricao: "Sanduicheira grill Philco",
    preco: 119,
    loja: "",
    categoria: "Eletroportáteis",
    emoji: "🥪",
    img: "img/produtos/sanduicheira-philco.jpg",
    link: "",
  },
  {
    id: "p11",
    nome: "Smart TV OLED",
    descricao: "Smart TV OLED",
    preco: 3499,
    loja: "",
    categoria: "Lazer",
    emoji: "📺",
    img: "img/produtos/smart-tv-oled.jpg",
    link: "",
  },
  {
    id: "p12",
    nome: "Roupão para o Casal",
    descricao: "Roupão de banho para o casal",
    preco: 159,
    loja: "",
    categoria: "Cama & Banho",
    emoji: "🛁",
    img: "img/produtos/roupao-casal.jpg",
    link: "",
  },
  {
    id: "p13",
    nome: "Quadro da Virgem do Caminho",
    descricao: "Quadro da Virgem do Caminho",
    preco: 189,
    loja: "",
    categoria: "Casa",
    emoji: "🖼️",
    img: "img/produtos/quadro-virgem-caminho.jpg",
    link: "",
  },
  {
    id: "p14",
    nome: "Batedeira",
    descricao: "Batedeira Philco",
    preco: 329,
    loja: "",
    categoria: "Eletroportáteis",
    emoji: "🎂",
    img: "img/produtos/batedeira-philco.jpg",
    link: "",
  },
  {
    id: "p15",
    nome: "Alexa",
    descricao: "Alexa — assistente virtual",
    preco: 349,
    loja: "",
    categoria: "Lazer",
    emoji: "🔊",
    img: "img/produtos/alexa.jpg",
    link: "",
  },
  {
    id: "p16",
    nome: "Lava e Seca",
    descricao: "Lava e seca Philco",
    preco: 3299,
    loja: "",
    categoria: "Eletroportáteis",
    emoji: "🧺",
    img: "img/produtos/lava-e-seca-philco.jpg",
    link: "",
  },
  {
    id: "p17",
    nome: "Tanquinho de Roupa",
    descricao: "Tanquinho de roupa",
    preco: 699,
    loja: "",
    categoria: "Casa",
    emoji: "🫧",
    img: "img/produtos/tanquinho-roupa.jpg",
    link: "",
  },
  {
    id: "p18",
    nome: "Mesa de Computador",
    descricao: "Mesa de computador",
    preco: 449,
    loja: "",
    categoria: "Casa",
    emoji: "🖥️",
    img: "img/produtos/mesa-computador.jpg",
    link: "",
  },
  {
    id: "p19",
    nome: "Chuteira Tamanho 42",
    descricao: "Chuteira tamanho 42",
    preco: 299,
    loja: "",
    categoria: "Pessoal",
    emoji: "⚽",
    img: "img/produtos/chuteira-42.jpg",
    link: "",
  },
  {
    id: "p20",
    nome: "Kit de Skincare",
    descricao: "Kit de skincare completo",
    preco: 199,
    loja: "",
    categoria: "Pessoal",
    emoji: "🧴",
    img: "img/produtos/kit-skincare.jpg",
    link: "",
  },
  {
    id: "p21",
    nome: "Guarda-Roupa Odisseia",
    descricao: "Guarda-roupa Odisseia 6 portas, 2 gavetas, com espelho",
    preco: 1299,
    loja: "",
    categoria: "Casa",
    emoji: "🚪",
    img: "img/produtos/guarda-roupa-odisseia.jpg",
    link: "",
  },
  {
    id: "p22",
    nome: "PS5 para o Noivo",
    descricao: "PlayStation 5 — presente do noivo 😉",
    preco: 3999,
    loja: "",
    categoria: "Lazer",
    emoji: "🎮",
    img: "img/produtos/ps5.jpg",
    link: "",
  },
  {
    id: "p23",
    nome: "Cristaleira Londres",
    descricao: "Cristaleira 2 portas de vidro, 1 gaveta — Londres LB",
    preco: 1499,
    loja: "",
    categoria: "Casa",
    emoji: "🥃",
    img: "img/produtos/cristaleira-londres.jpg",
    link: "",
  },
  {
    id: "p24",
    nome: "Um Dia de Spa",
    descricao: "Cota para um dia de spa para a noiva 💆‍♀️",
    preco: 299,
    loja: "",
    categoria: "Lua de Mel",
    emoji: "💆‍♀️",
    img: "img/produtos/dia-de-spa.jpg",
    link: "",
  },
  {
    id: "p25",
    nome: "Panela Elétrica",
    descricao: "Panela elétrica Philco",
    preco: 199,
    loja: "",
    categoria: "Eletroportáteis",
    emoji: "🍲",
    img: "img/produtos/panela-eletrica-philco.jpg",
    link: "",
  },
];

/* Estado inicial vazio — lista real, sem reservas de exemplo */
const ESTADO_INICIAL_EXEMPLO = {};
